name=OENENetCommon
version=1.0.0
author=andreaBernasconi
maintainer=andreaBernasconi
sentence=Common utilities for OENENet firmware.
paragraph=Includes Logging, OSC utilities, and general helpers.
category=Communication
architectures=*